### ISSUE TITLE
RSS/Atom feed for your blog

### ISSUE THREAD

**Issue by haroldcarr** [jorisroovers/casa#4]
Does your blog have an RSS/Atom feed.
My feedreader, https://bazqux.com/ , can't find it.

Thanks for the updated Home Assistant article!

**Comment by jorisroovers** [comment]
Thanks for your interest. It does not, but let me have a look at that :-) Might take a bit.

I know it's not the same, but I do send out notifications via email (no other spam): https://tinyletter.com/jorisroovers

**Comment by haroldcarr** [comment]
If possible, please add a feed.
Thanks for the email notification offer, but I avoid those.
